services:
  app:
    build: .
    container_name: "app"
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres
    container_name: "db"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:

networks:
  app_network:
    driver: bridge
