name: build auth

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true

      - name: checkout code into the go module directory
        uses: actions/checkout@v4

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: build
        run: go build -o bin/main ./cmd/main.go

      - name: notify slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_TITLE: ${{ github.workflow }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}