name: push docker image to registry

on:
  release:
    types:
      - published

jobs:
  push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code into the go module directory
        uses: actions/checkout@v3

      - name: set docker tag
        id: set-docker-tag
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: login to docker, build image and push
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ secrets.DOCKERHUB_USERNAME }}/demo
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "latest,${{ steps.set-docker-tag.outputs.release-version }}"